### ISSUE TITLE
relay-compiler ts definitions

### ISSUE THREAD

**Issue by n1ru4l** [n1ru4l/relay-compiler-repl#3]
there are none available, create-react-app did ignore the ones I tried to add in react-app.env.d.ts. Need to figure out why.

**Comment by sibelius** [comment]
check here https://github.com/relay-tools/relay-compiler-language-typescript/tree/master/types

we can move them to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by n1ru4l** [comment]
@sibelius Yes that would be awesome! For now, I will probably copy paste em over.

**Comment by n1ru4l** [comment]
they are now available on npm @types/relay-compiler

**Comment by n1ru4l** [comment]
Fixed in 1bfe4d5765e66133e04d31b24bf62fac7bb6645b
